name: promptcraft
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - nodejs=18
  - npm=9
  - pip
  - git
  - pip:
    - react-scripts
prefix: /Users/$USER/miniconda3/envs/promptcraft